package kr.co.gudi.member.dto;

public enum MemberAuthority{
	MARKETING, OPERATIONS, SUPPORT, EXECUTIVE,
	
	AD_TEAM_EMP, PLANNING_TEAM_EMP, DESIGN_TEAM_EMP,
	
	DISTRIBUTION_TEAM_EMP, CORYRIGHT_TEAM_EMP, CONTRACT_TEAM_EMP, STRATEGY_TEAM_EMP,
	
	SUPPORT_TEAM_EMP, ADMINIST_TEAM_EMP, REPRESENT_TEAM_EMP,
	
	CEO, PRESIDENT, SENIOR, EXEPRESIDENT;
}
